package com.pivotal.cf.broker.model;

import java.io.Serializable;
import java.util.Date;

public class PaasDockerContainers implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paas_docker_containers.id
     *
     * @mbggenerated Sat Feb 28 10:37:24 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paas_docker_containers.img_id
     *
     * @mbggenerated Sat Feb 28 10:37:24 CST 2015
     */
    private String imgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paas_docker_containers.img_name
     *
     * @mbggenerated Sat Feb 28 10:37:24 CST 2015
     */
    private String imgName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paas_docker_containers.container_id
     *
     * @mbggenerated Sat Feb 28 10:37:24 CST 2015
     */
    private String containerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paas_docker_containers.container_name
     *
     * @mbggenerated Sat Feb 28 10:37:24 CST 2015
     */
    private String containerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paas_docker_containers.container_ip
     *
     * @mbggenerated Sat Feb 28 10:37:24 CST 2015
     */
    private String containerIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paas_docker_containers.container_port
     *
     * @mbggenerated Sat Feb 28 10:37:24 CST 2015
     */
    private String containerPort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paas_docker_containers.container_user
     *
     * @mbggenerated Sat Feb 28 10:37:24 CST 2015
     */
    private String containerUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paas_docker_containers.container_passwd
     *
     * @mbggenerated Sat Feb 28 10:37:24 CST 2015
     */
    private String containerPasswd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paas_docker_containers.container_volumes
     *
     * @mbggenerated Sat Feb 28 10:37:24 CST 2015
     */
    private String containerVolumes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paas_docker_containers.container_db
     *
     * @mbggenerated Sat Feb 28 10:37:24 CST 2015
     */
    private String containerDb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paas_docker_containers.container_env
     *
     * @mbggenerated Sat Feb 28 10:37:24 CST 2015
     */
    private String containerEnv;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paas_docker_containers.remark
     *
     * @mbggenerated Sat Feb 28 10:37:24 CST 2015
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paas_docker_containers.created_at
     *
     * @mbggenerated Sat Feb 28 10:37:24 CST 2015
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paas_docker_containers.updated_at
     *
     * @mbggenerated Sat Feb 28 10:37:24 CST 2015
     */
    private Date updatedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table paas_docker_containers
     *
     * @mbggenerated Sat Feb 28 10:37:24 CST 2015
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paas_docker_containers.id
     *
     * @return the value of paas_docker_containers.id
     *
     * @mbggenerated Sat Feb 28 10:37:24 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paas_docker_containers.id
     *
     * @param id the value for paas_docker_containers.id
     *
     * @mbggenerated Sat Feb 28 10:37:24 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paas_docker_containers.img_id
     *
     * @return the value of paas_docker_containers.img_id
     *
     * @mbggenerated Sat Feb 28 10:37:24 CST 2015
     */
    public String getImgId() {
        return imgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paas_docker_containers.img_id
     *
     * @param imgId the value for paas_docker_containers.img_id
     *
     * @mbggenerated Sat Feb 28 10:37:24 CST 2015
     */
    public void setImgId(String imgId) {
        this.imgId = imgId == null ? null : imgId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paas_docker_containers.img_name
     *
     * @return the value of paas_docker_containers.img_name
     *
     * @mbggenerated Sat Feb 28 10:37:24 CST 2015
     */
    public String getImgName() {
        return imgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paas_docker_containers.img_name
     *
     * @param imgName the value for paas_docker_containers.img_name
     *
     * @mbggenerated Sat Feb 28 10:37:24 CST 2015
     */
    public void setImgName(String imgName) {
        this.imgName = imgName == null ? null : imgName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paas_docker_containers.container_id
     *
     * @return the value of paas_docker_containers.container_id
     *
     * @mbggenerated Sat Feb 28 10:37:24 CST 2015
     */
    public String getContainerId() {
        return containerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paas_docker_containers.container_id
     *
     * @param containerId the value for paas_docker_containers.container_id
     *
     * @mbggenerated Sat Feb 28 10:37:24 CST 2015
     */
    public void setContainerId(String containerId) {
        this.containerId = containerId == null ? null : containerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paas_docker_containers.container_name
     *
     * @return the value of paas_docker_containers.container_name
     *
     * @mbggenerated Sat Feb 28 10:37:24 CST 2015
     */
    public String getContainerName() {
        return containerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paas_docker_containers.container_name
     *
     * @param containerName the value for paas_docker_containers.container_name
     *
     * @mbggenerated Sat Feb 28 10:37:24 CST 2015
     */
    public void setContainerName(String containerName) {
        this.containerName = containerName == null ? null : containerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paas_docker_containers.container_ip
     *
     * @return the value of paas_docker_containers.container_ip
     *
     * @mbggenerated Sat Feb 28 10:37:24 CST 2015
     */
    public String getContainerIp() {
        return containerIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paas_docker_containers.container_ip
     *
     * @param containerIp the value for paas_docker_containers.container_ip
     *
     * @mbggenerated Sat Feb 28 10:37:24 CST 2015
     */
    public void setContainerIp(String containerIp) {
        this.containerIp = containerIp == null ? null : containerIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paas_docker_containers.container_port
     *
     * @return the value of paas_docker_containers.container_port
     *
     * @mbggenerated Sat Feb 28 10:37:24 CST 2015
     */
    public String getContainerPort() {
        return containerPort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paas_docker_containers.container_port
     *
     * @param containerPort the value for paas_docker_containers.container_port
     *
     * @mbggenerated Sat Feb 28 10:37:24 CST 2015
     */
    public void setContainerPort(String containerPort) {
        this.containerPort = containerPort == null ? null : containerPort.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paas_docker_containers.container_user
     *
     * @return the value of paas_docker_containers.container_user
     *
     * @mbggenerated Sat Feb 28 10:37:24 CST 2015
     */
    public String getContainerUser() {
        return containerUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paas_docker_containers.container_user
     *
     * @param containerUser the value for paas_docker_containers.container_user
     *
     * @mbggenerated Sat Feb 28 10:37:24 CST 2015
     */
    public void setContainerUser(String containerUser) {
        this.containerUser = containerUser == null ? null : containerUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paas_docker_containers.container_passwd
     *
     * @return the value of paas_docker_containers.container_passwd
     *
     * @mbggenerated Sat Feb 28 10:37:24 CST 2015
     */
    public String getContainerPasswd() {
        return containerPasswd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paas_docker_containers.container_passwd
     *
     * @param containerPasswd the value for paas_docker_containers.container_passwd
     *
     * @mbggenerated Sat Feb 28 10:37:24 CST 2015
     */
    public void setContainerPasswd(String containerPasswd) {
        this.containerPasswd = containerPasswd == null ? null : containerPasswd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paas_docker_containers.container_volumes
     *
     * @return the value of paas_docker_containers.container_volumes
     *
     * @mbggenerated Sat Feb 28 10:37:24 CST 2015
     */
    public String getContainerVolumes() {
        return containerVolumes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paas_docker_containers.container_volumes
     *
     * @param containerVolumes the value for paas_docker_containers.container_volumes
     *
     * @mbggenerated Sat Feb 28 10:37:24 CST 2015
     */
    public void setContainerVolumes(String containerVolumes) {
        this.containerVolumes = containerVolumes == null ? null : containerVolumes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paas_docker_containers.container_db
     *
     * @return the value of paas_docker_containers.container_db
     *
     * @mbggenerated Sat Feb 28 10:37:24 CST 2015
     */
    public String getContainerDb() {
        return containerDb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paas_docker_containers.container_db
     *
     * @param containerDb the value for paas_docker_containers.container_db
     *
     * @mbggenerated Sat Feb 28 10:37:24 CST 2015
     */
    public void setContainerDb(String containerDb) {
        this.containerDb = containerDb == null ? null : containerDb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paas_docker_containers.container_env
     *
     * @return the value of paas_docker_containers.container_env
     *
     * @mbggenerated Sat Feb 28 10:37:24 CST 2015
     */
    public String getContainerEnv() {
        return containerEnv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paas_docker_containers.container_env
     *
     * @param containerEnv the value for paas_docker_containers.container_env
     *
     * @mbggenerated Sat Feb 28 10:37:24 CST 2015
     */
    public void setContainerEnv(String containerEnv) {
        this.containerEnv = containerEnv == null ? null : containerEnv.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paas_docker_containers.remark
     *
     * @return the value of paas_docker_containers.remark
     *
     * @mbggenerated Sat Feb 28 10:37:24 CST 2015
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paas_docker_containers.remark
     *
     * @param remark the value for paas_docker_containers.remark
     *
     * @mbggenerated Sat Feb 28 10:37:24 CST 2015
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paas_docker_containers.created_at
     *
     * @return the value of paas_docker_containers.created_at
     *
     * @mbggenerated Sat Feb 28 10:37:24 CST 2015
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paas_docker_containers.created_at
     *
     * @param createdAt the value for paas_docker_containers.created_at
     *
     * @mbggenerated Sat Feb 28 10:37:24 CST 2015
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paas_docker_containers.updated_at
     *
     * @return the value of paas_docker_containers.updated_at
     *
     * @mbggenerated Sat Feb 28 10:37:24 CST 2015
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paas_docker_containers.updated_at
     *
     * @param updatedAt the value for paas_docker_containers.updated_at
     *
     * @mbggenerated Sat Feb 28 10:37:24 CST 2015
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_docker_containers
     *
     * @mbggenerated Sat Feb 28 10:37:24 CST 2015
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", imgId=").append(imgId);
        sb.append(", imgName=").append(imgName);
        sb.append(", containerId=").append(containerId);
        sb.append(", containerName=").append(containerName);
        sb.append(", containerIp=").append(containerIp);
        sb.append(", containerPort=").append(containerPort);
        sb.append(", containerUser=").append(containerUser);
        sb.append(", containerPasswd=").append(containerPasswd);
        sb.append(", containerVolumes=").append(containerVolumes);
        sb.append(", containerDb=").append(containerDb);
        sb.append(", containerEnv=").append(containerEnv);
        sb.append(", remark=").append(remark);
        sb.append(", createdAt=").append(createdAt);
        sb.append(", updatedAt=").append(updatedAt);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}