CREATE TABLE IF NOT EXISTS mysqldockerserviceinstance (
   SERVICE_INSTANCE_ID   VARCHAR(128) NOT NULL,

   SERVICE_ID   VARCHAR(64) NOT NULL,
   PLAN_ID   VARCHAR(64) NOT NULL,
   ORGANIZATION_GUID   VARCHAR(128) NOT NULL,
   SPACE_GUID   VARCHAR(128) NOT NULL,
   DASHBOARD_URL   VARCHAR(128) NOT NULL,
   CONTAINER_ID   VARCHAR(128) NOT NULL,
   CONTAINER_HOST   VARCHAR(64) NOT NULL,
   CONTAINER_PORT   VARCHAR(64) NOT NULL,
   CONTAINER_USER   VARCHAR(64) NOT NULL,
   CONTAINER_PASSWD   VARCHAR(64) NOT NULL,
   CONTAINER_DB   VARCHAR(64) NOT NULL,

   PRIMARY KEY (SERVICE_INSTANCE_ID)
);

CREATE TABLE IF NOT EXISTS mongodbdockerserviceinstance (
   SERVICE_INSTANCE_ID   VARCHAR(128) NOT NULL,

   SERVICE_ID   VARCHAR(64) NOT NULL,
   PLAN_ID   VARCHAR(64) NOT NULL,
   ORGANIZATION_GUID   VARCHAR(128) NOT NULL,
   SPACE_GUID   VARCHAR(128) NOT NULL,
   DASHBOARD_URL   VARCHAR(128) NOT NULL,
   CONTAINER_ID   VARCHAR(128) NOT NULL,
   CONTAINER_HOST   VARCHAR(64) NOT NULL,
   CONTAINER_PORT   VARCHAR(64) NOT NULL,
   CONTAINER_USER   VARCHAR(64) NOT NULL,
   CONTAINER_PASSWD   VARCHAR(64) NOT NULL,
   CONTAINER_DB   VARCHAR(64) NOT NULL,

   PRIMARY KEY (SERVICE_INSTANCE_ID)
);

CREATE TABLE IF NOT EXISTS postgresqldockerserviceinstance (
   SERVICE_INSTANCE_ID   VARCHAR(128) NOT NULL,

   SERVICE_ID   VARCHAR(64) NOT NULL,
   PLAN_ID   VARCHAR(64) NOT NULL,
   ORGANIZATION_GUID   VARCHAR(128) NOT NULL,
   SPACE_GUID   VARCHAR(128) NOT NULL,
   DASHBOARD_URL   VARCHAR(128) NOT NULL,
   CONTAINER_ID   VARCHAR(128) NOT NULL,
   CONTAINER_HOST   VARCHAR(64) NOT NULL,
   CONTAINER_PORT   VARCHAR(64) NOT NULL,
   CONTAINER_USER   VARCHAR(64) NOT NULL,
   CONTAINER_PASSWD   VARCHAR(64) NOT NULL,
   CONTAINER_DB   VARCHAR(64) NOT NULL,

   PRIMARY KEY (SERVICE_INSTANCE_ID)
);

CREATE TABLE IF NOT EXISTS redisdockerserviceinstance (
   SERVICE_INSTANCE_ID   VARCHAR(128) NOT NULL,

   SERVICE_ID   VARCHAR(64) NOT NULL,
   PLAN_ID   VARCHAR(64) NOT NULL,
   ORGANIZATION_GUID   VARCHAR(128) NOT NULL,
   SPACE_GUID   VARCHAR(128) NOT NULL,
   DASHBOARD_URL   VARCHAR(128) NOT NULL,
   CONTAINER_ID   VARCHAR(128) NOT NULL,
   CONTAINER_HOST   VARCHAR(64) NOT NULL,
   CONTAINER_PORT   VARCHAR(64) NOT NULL,
   CONTAINER_PASSWD   VARCHAR(64) NOT NULL,

   PRIMARY KEY (SERVICE_INSTANCE_ID)
);

CREATE TABLE IF NOT EXISTS memcacheddockerserviceinstance (
   SERVICE_INSTANCE_ID   VARCHAR(128) NOT NULL,

   SERVICE_ID   VARCHAR(64) NOT NULL,
   PLAN_ID   VARCHAR(64) NOT NULL,
   ORGANIZATION_GUID   VARCHAR(128) NOT NULL,
   SPACE_GUID   VARCHAR(128) NOT NULL,
   DASHBOARD_URL   VARCHAR(128) NOT NULL,
   CONTAINER_ID   VARCHAR(128) NOT NULL,
   CONTAINER_HOST   VARCHAR(64) NOT NULL,
   CONTAINER_PORT   VARCHAR(64) NOT NULL,
   CONTAINER_USER   VARCHAR(64) NOT NULL,
   CONTAINER_PASSWD   VARCHAR(64) NOT NULL,

   PRIMARY KEY (SERVICE_INSTANCE_ID)
);

CREATE TABLE IF NOT EXISTS ServiceInstanceBinding (
   SERVICE_INSTANCE_BINDING_ID   VARCHAR(128) NOT NULL,

   SERVICE_INSTANCE_ID   VARCHAR(128) NOT NULL,
   CREDENTIALS   VARCHAR(512) NOT NULL,
   SYSLOG_DRAIN_URL   VARCHAR(128) NOT NULL,
   APP_GUID   VARCHAR(128) NOT NULL,

   PRIMARY KEY (SERVICE_INSTANCE_BINDING_ID)
);
